context:
  version: "6.17.1"

package:
  name: btrfs-progs
  version: ${{ version }}

source:
  - url: https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v${{ version }}.tar.xz
    sha256: a4be0a6ebb3c476427fb5d97b2cf027b0ccdb6b0c55ff16323320c1e8cb77658
    patches:
      - 0001-Install-udev-rules-inside-prefix.patch

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - autoconf >=2.60
    - automake
    - make
    - pkg-config
    # We override UDEVDIR in 0001-Install-udev-rules-inside-prefix.patch anyway
    # hence we can omit the libudev dependency and and compile for CentOS 6.
    # # Needs libudev >=190 which is not available on Centos 6.
    # # On Centos 7 it is provided by systemd-devel.
    # # - {{ cdt('libudev-devel') }}
    # # - sysroot_linux-64 >=2.17
    # # - {{ cdt('systemd-devel') }}
  host:
    - e2fsprogs-libs
    # Upstream requires libgcrypt >=1.8.0, but only >=1.8.5 has the pkgconfig files we want.
    - libgcrypt >=1.8.5
    - libgcrypt
    - lzo
    # Only need the libs, but util-linux doesn't offer a subpackage for it.
    # - util-linux-libs
    - util-linux
    - zstd >=1.0.0
    - zstd
    - zlib
    - libudev
  run:

tests:
  - script:
      - btrfs --help
      - btrfs --version
  - package_contents:
      include:
        - btrfs/version.h
        - btrfsutil.h
      lib:
        - btrfs
        - btrfsutil
      files:
        - lib/pkgconfig/libbtrfsutil.pc

about:
  homepage: https://btrfs.wiki.kernel.org
  repository: https://github.com/kdave/btrfs-progs
  documentation: https://btrfs.wiki.kernel.org/index.php/Category:Manpage
  license: GPL-2.0-only AND LGPL-3.0-or-later
  license_file:
    - COPYING
    - libbtrfsutil/COPYING
  summary: Userspace utilities to manage btrfs filesystems.

extra:
  recipe-maintainers:
    - mbargull
    - wolfv
